[workspace]
authors = ["Gabriel Turmail <g.turmail@imagingengineeringllc.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]
preview = ["pixi-build"]

[dependencies]
pixi-nng-example = { path = "." }  # for local testing
python = "*"                       # optional if you add bindings later

[package]
name = "pixi-nng-example"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "0.*" }

[package.host-dependencies]
cmake = ">=3.22"
ninja = "*"
nng = ">=1.11,<2"
clang = "*"

[package.build.config]
extra-args = ["-DCMAKE_BUILD_TYPE=Release"]